spring:
  application:
    name: content
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.119.186:3306/zhuoyue_content?serverTimezone=UTC&characterEncoding=utf8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
server:
  port: 8003
mybatis:
  configuration:
    use-generated-keys: true