spring:
  application:
    name: search
  datasource:
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.95.119.186:3306/zhuoyue_article?serverTimezone=UTC&characterEncoding=utf8
  cloud:
    alibaba:
      seata:
        # 这里要和file.conf文件中一致
        tx-service-group: my_test_tx_group
  redis:
    host: 47.95.215.227
    password: 123456
  data:
    elasticsearch:
      cluster-nodes: 47.95.119.186:9300
      cluster-name: elasticsearch
  main:
    allow-bean-definition-overriding: true
server:
  port: 8006
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 300000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000